package org.acme.insurance;

import org.acme.insurance.Driver
import org.acme.insurance.Policy
import org.acme.insurance.Rejection


rule "prueba2"
salience 2000000
    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <= 1)
	    policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        System.out.println("fired rule " + kcontext.getRule().getName());
        
		

end