package org.acme.insurance;

import org.acme.insurance.Driver
import org.acme.insurance.Policy
import org.acme.insurance.Rejection


rule "prueba2"
salience 2000000
    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <= 1)
	    policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(450)};
        System.out.println("fired rule " + kcontext.getRule().getName());
        Rejection fact0 = new Rejection();
		fact0.setReason( "Esto es una prueba2" );
		insert( fact0 );
		System.out.println("fired rule " + kcontext.getRule().getName());
		System.out.println(fact0.getReason());
		

end