package org.acme.insurance.policyquote;

import java.lang.Number;

rule "AccidentSurcharge"
	dialect "mvel"
	no-loop true
	lock-on-active true
	when
		driver : Driver(numberOfAccidents > 2)
		policy : Policy(policyType ==  "AUTO",priceSurcharge == null)
	then
		modify(policy) {priceSurcharge = 200}
		System.out.println("fired rule " + kcontext.getRule().getName());
end

rule "AccidentSurcharge2"
	dialect "mvel"
	no-loop true
	lock-on-active true
	when
		driver : Driver(numberOfAccidents > 2)
		policy : Policy(policyType ==  "AUTO",priceSurcharge > 0)
	then
		modify(policy) {priceSurcharge = 200 + policy.priceSurcharge}
		System.out.println("fired rule " + kcontext.getRule().getName());
end