package org.acme.insurance.policyquote;

import java.lang.Number;
import org.acme.insurance.Accident

rule "AccidentSurcharge"
    salience 1000
	dialect "mvel"
	no-loop true
	//lock-on-active true
	when
		driver : Driver(numberOfAccidents > 2)
		policy : Policy(policyType ==  "AUTO",priceSurcharge == null)
		not Accident( )
		not Rejection()
	then
		modify(policy) {priceSurcharge = 200}
		System.out.println("fired rule " + kcontext.getRule().getName());
		update(policy)
		Accident fact0 = new Accident();
		insert( fact0 );
end

rule "AccidentSurcharge2"
    salience 1000
	dialect "mvel"
	no-loop true
	//lock-on-active true
	when
		driver : Driver(numberOfAccidents > 2)
		policy : Policy(policyType ==  "AUTO",priceSurcharge > 0)
		not Accident( )
		not Rejection()
	then
		modify(policy) {priceSurcharge = 200 + policy.priceSurcharge}
		update(policy)
		System.out.println("fired rule " + kcontext.getRule().getName());
		Accident fact0 = new Accident();
		insert( fact0 );
end