package org.acme.insurance.policyquote;

import java.lang.Number;

rule "NewerVehicleSurcharge"
	dialect "mvel"
	no-loop true
	lock-on-active true
	when
		policy : Policy(vehicleYear > 2004, policyType ==  "AUTO",priceSurcharge == null)
	then
		modify(policy) {priceSurcharge = 100}
		System.out.println("fired rule " + kcontext.getRule().getName());
		update(policy)
end


rule "NewerVehicleSurcharge2"
	dialect "mvel"
	no-loop true
	lock-on-active true
	when
		policy : Policy(vehicleYear > 2004, policyType ==  "AUTO",priceSurcharge > 0)
	then
		modify(policy) {priceSurcharge = 100 + policy.priceSurcharge}
		System.out.println("fired rule " + kcontext.getRule().getName());
		update(policy)
end