package org.acme.insurance.policyquote;

import java.lang.Number;
import org.acme.insurance.NoviceDriver



rule "NoviceDriverSurcharge"
	dialect "mvel"
	//lock-on-active true
	no-loop true
	when
		driver : Driver(age < 20)
		policy : Policy(priceSurcharge == null,policyType ==  "AUTO")
		not NoviceDriver( )
	then
		modify(policy) {priceSurcharge = 200}
		 System.out.println("fired rule " + kcontext.getRule().getName());
		 update(policy)
		NoviceDriver fact0 = new NoviceDriver();
		insert( fact0 );
end

rule "NoviceDriverSurcharge2"
	dialect "mvel"
	//lock-on-active true
	no-loop true
	when
		driver : Driver(age < 20)
		policy : Policy(priceSurcharge > 0,policyType ==  "AUTO")
		not NoviceDriver( )
	then
		modify(policy) {priceSurcharge = 200 + policy.priceSurcharge}
		 System.out.println("fired rule " + kcontext.getRule().getName());
		 update(policy)
		 NoviceDriver fact0 = new NoviceDriver();
		insert( fact0 );
end