package org.acme.insurance.policyquote

import org.acme.insurance.Driver
import org.acme.insurance.Policy
import org.acme.insurance.Rejection

rule "RiskyYouths"
//ruleflow-group "calculate"
    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfAccidents >= 1 || numberOfTickets >=2)
	policy : Policy(policyType == "AUTO")
	not Rejection()
    then
        //actions
        modify(policy) {setPrice(700)};
        System.out.println("fired rule " + kcontext.getRule().getName());

end